language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: IdISrLkzeRexIJ0SIko81oDeeZc30lyzFuJ5CjIGUkBkgPLjmuECb8PX//3g9c0hAC9nT8oaBhMsTGMS0fBmz7gywPf7KXDbAQnRuSpA6R/1CbatNCbNHe05L6qOjbTzGTgQgqBNiUwlWDyIavqmjSTjJ/S2dE7grQB+ZKjIEAVUmQGwWehXYbP4c4yaTcfhENcvIx9TpyKI8r44bOA+j955Uz1prTqzIPnd1DBHs5oCKqm3/EAD5ilb4HseTRVMXokc5MtGkBXHjRvHsMIOFbplDqI35FGrPfpMUisZw3ISjAGSjjWcrJObytKZxMWm/PeG0gPVix3xnKln9qmMIr/OF/bzyiSar47+8HV7VZPZ6IATnFixqvfSFyjajW/wCz8bEshHJGJHBdQLsA6XCSfMDgrna1KjVjUaxG70n9auvDEMs45w6zEmeH+N37rVmwmeoX+Nptlz3v3mvsNyz4ZbOrRbR3tsWCKPu1WLhi89EdJrpjy0HeTQFA/XFPSTV7Lq6ilGql+YdlGjWtGRcErfdE87zNWyO0ZEx1ne5XerV3I1itao6MW3LoSFZgWl441FY32icFFIek4DEzP6XoF4IDsjBNd8gTEcpEu4uIgujjuYHdf4xn4EYVlmpXdW4yQvqkK7C/Nnuo0A3OHyN1+uBZsgNP6HvcmihpC1Z04=
  app: what-does-brexit-mean
  on:
    repo: pikesley/whatdoesbrexitmean
